// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Un4YeAeHNtEvl-3pdrsjWurXPl3ecRU',
    appId: '1:614819447216:web:6af5e5aee82429164c1675',
    messagingSenderId: '614819447216',
    projectId: 'platform-converter-app',
    authDomain: 'platform-converter-app.firebaseapp.com',
    storageBucket: 'platform-converter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5GTsTbCuDxXtWsNK1Zy2uk0zRoUJFzK4',
    appId: '1:614819447216:android:c7b74846e81bcc1e4c1675',
    messagingSenderId: '614819447216',
    projectId: 'platform-converter-app',
    storageBucket: 'platform-converter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dTuy1AtWpAS3W3S_le_8DTHQtYgpmQ0',
    appId: '1:614819447216:ios:fc4ba278a405a2364c1675',
    messagingSenderId: '614819447216',
    projectId: 'platform-converter-app',
    storageBucket: 'platform-converter-app.appspot.com',
    iosBundleId: 'com.example.platformConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8dTuy1AtWpAS3W3S_le_8DTHQtYgpmQ0',
    appId: '1:614819447216:ios:fc4ba278a405a2364c1675',
    messagingSenderId: '614819447216',
    projectId: 'platform-converter-app',
    storageBucket: 'platform-converter-app.appspot.com',
    iosBundleId: 'com.example.platformConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Un4YeAeHNtEvl-3pdrsjWurXPl3ecRU',
    appId: '1:614819447216:web:67314f7802871df04c1675',
    messagingSenderId: '614819447216',
    projectId: 'platform-converter-app',
    authDomain: 'platform-converter-app.firebaseapp.com',
    storageBucket: 'platform-converter-app.appspot.com',
  );
}
